# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cf40e76151e23c182cdbbdd345a6e91ec0702f9cafab9ddff744c41f07d311ab4ff61b969491d1472923086e4ec3814a5669869facb6789ce20cf050f7c0dd0

test:
  secret_key_base: abdf3d0466a6450d2420174dc3c3ac467656f4fa62b987f4060c5211fb0ee7546f7237c5f62ff7c6776d8e481c3a78893978500077a825bdf013a0b14f05521d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
